

clear matfrostjuliacall
mh = mexhost();
s= mh.feval("matfrostjuliacall", ...
    struct( ...
        "a", struct("a",double([1]), "b",int64(2),"c",double(3), "d", "wefwwefweagaergaerhergregreg"),...
        "b", struct("a",double([1]), "b",int64(2),"c",double(3), "d", "wefwefwefweeagaergaerhergregreg")...
    ));